export const dummyGolfCourses = [
  {
    property: "Richmond Hill Golf Club",
    latitude: 43.8372,
    longitude: -79.4526,
    city: "Toronto",
    country: "Canada",
    holes: 18,
    public: true,
    range: true,
    rating: 4.2,
  },
  {
    property: "Summit Golf & Country Club",
    latitude: 43.9181,
    longitude: -79.446,
    city: "Toronto",
    country: "Canada",
    holes: 18,
    public: false,
    rating: 4.6,
    range: false,
  },
  {
    property: "Summit Golf & Country Club",
    latitude: 43.9181,
    longitude: -79.446,
    city: "Toronto",
    country: "Canada",
    holes: 18,
    public: false,
    range: false,
    rating: 4.6,
  },
  {
    property: "King Valley Golf Club",
    latitude: 44.000784,
    longitude: -79.5095372,
    city: "Toronto",
    country: "Canada",
    holes: 18,
    public: false,
    range: true,
    rating: 4.6,
  },
  {
    property: "DiamondBank Golf Club",
    latitude: 43.9609165,
    longitude: -79.4147022,
    city: "Toronto",
    country: "Canada",
    holes: 18,
    public: false,
    range: true,
    rating: 4.2,
  },
];
